inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config/**/*"
    - "spec/*"
    - "Gemfile"
  TargetRubyVersion: 3.1.4
  
Layout/HashAlignment:
    Enabled: false
